### ISSUE TITLE
Firebase messaging

### ISSUE THREAD

**Issue by PMLS3** [smorcuend/nuxt3-firebase-auth#1]
Hi, thanks for  a great repo...

This is not an issue but a request. I am trying to get firebase messaging working but keep getting errors. Have you been able to get it working with Nuxt3?

**Comment by semocodev** [comment]
Hi @PMLS3, thanks for your appreciation. 

For FCM you can try this module: https://github.com/becem-gharbi/nuxt-fcm 

FCM needs client side Firebase SDK to work

**Comment by PMLS3** [comment]
> Hi @PMLS3, thanks for your appreciation.
> 
> For FCM you can try this module: https://github.com/becem-gharbi/nuxt-fcm
> 
> FCM needs client side Firebase SDK to work

You are a legend, thanks
